# Cloud Build config: build image and deploy to Cloud Run
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/ivytechchallenge:$SHORT_SHA','.']

  # Deploy step using gcloud (requires Cloud SDK image)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ivytechchallenge \
          --image gcr.io/$PROJECT_ID/ivytechchallenge:$SHORT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080

images:
  - 'gcr.io/$PROJECT_ID/ivytechchallenge:$SHORT_SHA'
